workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    environment:
      vars:
        KEYSTORE_PASSWORD: rootazezo
        KEY_ALIAS: exlto_tts_key
        KEY_PASSWORD: rootazezo
    scripts:
      - name: Grant Gradlew Permission
        script: chmod +x gradlew
      - name: Ensure Gradle Plugin Repositories
        script: |
          echo "pluginManagement { repositories { google(); gradlePluginPortal(); mavenCentral() } }" >> settings.gradle.kts
      - name: Clean Project
        script: ./gradlew clean
      - name: Build Release APK
        script: |
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=release-key.jks \
            -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$KEY_PASSWORD
    artifacts:
      - app/build/outputs/**/*.apk