name: Android Release Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Grant Gradlew Permission
        run: chmod +x gradlew

      - name: Ensure Gradle Plugin Repositories
        run: |
          echo "pluginManagement { repositories { google(); gradlePluginPortal(); mavenCentral() } }" >> settings.gradle.kts

      - name: Clean Project
        run: ./gradlew clean

      - name: Build Release APK
        run: |
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=release-key.jks \
            -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/**/*.apk